SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS boards;
DROP TABLE IF EXISTS favorites;
DROP TABLE IF EXISTS event_targets;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS targets;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS prefectures;
DROP TABLE IF EXISTS event_participants;
DROP TABLE IF EXISTS signup_logs;


SET FOREIGN_KEY_CHECKS = 1;